# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - file://prompts/summarize_sgp.md

providers:
  - id: bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0

defaultTest:
  options:
    provider: bedrock:us.anthropic.claude-3-5-sonnet-20241022-v2:0

tests:
  - vars:
      data: file://tests/sgp_tests.txt
    assert:
      # For more information on model-graded evals, see https://promptfoo.dev/docs/configuration/expected-outputs/model-graded
      - type: llm-rubric
        value: there should be fewer than 3 bullet points

d